### ISSUE TITLE
Instruction for installing and using xcsync tool is not complete

### ISSUE THREAD

**Issue by Saratsin** [dotnet/xcsync#144]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Framework version

net8.0-*

### Describe the bug

The installation process described in [this instruction](https://github.com/dotnet/xcsync/blob/main/docs/using-latest-daily.md) is not complete.
In fact, I had to run the build in release configuration, then add path to this release folder (under .net8) into the PATH, and only then I was able to run xcsync in my project. Also I had to download and update my net8.0 verison as well (since I had not the latest one). 

Ideally, I would need just to call `brew install xcsync` and it would do all the installation processes for me so I would be able to use `xcsync` command from the console anywhere in the system

### Expected Behavior

I follow the instructions of the installation, and as a result able to use the tool in my project

### Steps To Reproduce

Follow only the instructions provided in [this file](https://github.com/dotnet/xcsync/blob/main/docs/using-latest-daily.md)

**Comment by mcumming** [comment]
Hi @Saratsin, 
Thank you for the report, we are reviewing the instructions and will update them as needed. Please note that `xcsync` is now distributed as a .NET Tool and you can use `dotnet tool install -g dotnet-xcsync` to install it globally from NuGet.org.

**Comment by snechaev** [comment]
@mcumming , I don't think that the current version of the manual is complete. I used `dotnet tool install --global dotnet-xcsync --prerelease` as prescribed and then was unable to run the `xcsync` command - `zsh: command not found: xcsync` even after restarting the terminal. Looks like I need to add something to the `%path%` manually and it might be a good idea to mention this in the manual.

I'm using macOS 14.6.1 .

**Comment by mcumming** [comment]
> [@mcumming](https://github.com/mcumming) , I don't think that the current version of the manual is complete. I used `dotnet tool install --global dotnet-xcsync --prerelease` as prescribed and then was unable to run the `xcsync` command - `zsh: command not found: xcsync` even after restarting the terminal. Looks like I need to add something to the `%path%` manually and it might be a good idea to mention this in the manual.
> 
> I'm using macOS 14.6.1 .

Was the terminal within VS Code? I've noticed that recently that closing a terminal and opening a new one within VS Code does not get a fresh environment from the system, only from the parent VS Code process.

**Comment by snechaev** [comment]
> Was the terminal within VS Code
No, I tried the system terminal, the iTerm2 and the terminal, embedded into the Rider IDE.

> that closing a terminal and opening a new one within VS Code does not get a fresh 
By the "restarting the terminal" I mean closing the process (Terminal or IDE) completely (Cmd+Q) and starting it again. So it looks like it is not my case (but I'm not sure, I did not tried to completely restart macOS ).
