### ISSUE TITLE
Help needed: Implementing "Sign in with Google" in .NET MAUI

### ISSUE THREAD

**Issue by NazrinAli12** [dotnet/xcsync#182]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hi dotnet,

I am currently learning .NET MAUI and trying to implement the "Sign in with Google" feature. However, I am facing some difficulties, as I need to do this without using Microsoft Azure, as per my teacher's recommendation.

Could you please guide me on how to implement this feature or share any resources or sample code that could help? I would greatly appreciate your support!

Thank you in advance for your time and help.

Best regards,
Nazrin

### Describe the solution you'd like

Hi dotnet,

I am currently learning .NET MAUI and trying to implement the "Sign in with Google" feature. However, I am facing some difficulties, as I need to do this without using Microsoft Azure, as per my teacher's recommendation.

Could you please guide me on how to implement this feature or share any resources or sample code that could help? I would greatly appreciate your support!

Thank you in advance for your time and help.

Best regards,
Nazrin

### Additional context

Hi dotnet,

I am currently learning .NET MAUI and trying to implement the "Sign in with Google" feature. However, I am facing some difficulties, as I need to do this without using Microsoft Azure, as per my teacher's recommendation.

Could you please guide me on how to implement this feature or share any resources or sample code that could help? I would greatly appreciate your support!

Thank you in advance for your time and help.

Best regards,
Nazrin

**Comment by dalexsoto** [comment]
Hello! Unfortunately this request is outside of the scope of our support, your question is more suited for the https://stackoverflow.com/ forum or our tech community forum https://learn.microsoft.com/answers

**Comment by NazrinAli12** [comment]
Thank you for answering my question
